name: Build and Deploy Documentation

# Trigger on pushes to main and on tag pushes (e.g., v1.0.0)
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # adjust if needed

      - name: Install Dependencies
        run: |
          # Install your package (editable mode to ensure __version__ is available)
          pip install -e .
          # Install Sphinx and theme dependencies
          pip install sphinx sphinx-rtd-theme

      - name: Generate API Documentation
        run: |
          # Regenerate autodoc files (if needed)
          sphinx-apidoc -o docs/source/ src/itrails

      - name: Build HTML Documentation
        working-directory: docs
        run: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./docs/_build/html
